### PR TITLE
feat: stop many

### PR DESCRIPTION
**Pull request by gamaraan**
* add stopMany command
* update documentation to include stopMany
* add stopMany test

### CODE REVIEW

**Comment by AlexZeitler** [comment]
@gamaraan Looks like this PR includes the rm fix you mentioned here https://github.com/PDMLab/docker-compose/pull/199#issuecomment-1013754412 ?

**Comment by gamaraan** [comment]
> @gamaraan Looks like this PR includes the rm fix you mentioned here [#199 (comment)](https://github.com/PDMLab/docker-compose/pull/199#issuecomment-1013754412) ?

No, I've found out that compose.rm is actually working fine for multiple containers also, so I've reverted the _fix_. I was passing the wrong arguments.
```
let services = ['web','proxy']
compose.rm(options,services) //fails
compose.rm(options,...services) //works
```

**Comment by gamaraan** [comment]
Sorry for another push, needed to pass lint tests

**Comment by AlexZeitler** [comment]
@gamaraan thanks 👍 📦 @ 0.23.16 is now available on npm.

**Pull request merged**
