### PR TITLE
Add port command

### LINKED ISSUE #51: Get dynamic port
A `docker-compose.yml` allows to forward a service port to an undefined, ephemeral host port:
```
version: "3"
services:
  database:
    build: .
    ports:
     - "3000"
```
(reference: https://docs.docker.com/compose/compose-file/#ports)

The forwarded host port can be retrieved by the `port` subcommand: https://docs.docker.com/compose/reference/port/

### PR DESCRIPTION
**Pull request by LarsKumbier**
Adds the port command, closes #51

### CODE REVIEW

**Comment by AlexZeitler** [comment]
@LarsKumbier Thanks for you contribution. It's published on npm as `0.15.0`

**Comment by stefanmeschke** [comment]
Thanks for this feature.
I think it would be very nice, if the port command returns only the port and not the whole address. And it is missing in the docs. :)

Do you agree? Should I raise a PR?

**Comment by AlexZeitler** [comment]
@stefanmeschke Makes sense to me.

@LarsKumbier Would this break something for you aside from only getting the port?
@Steveb-p Any thoughts?

**Comment by Steveb-p** [comment]
@AlexZeitler usually I believe we do not "enhance" original `docker-compose` responses. In this case, reading the port from the output is rather trivial, so introducing a special case might not be worth it.

After all, all you need to do to read the port from the output would then be as simple as
```javascript
const output = "0.0.0.0:2181"
const pos = output.indexOf(":")
const port = output.slice(pos + 1)
```

**Comment by LarsKumbier** [comment]
yeah, but it get's more complicated with ipv6, error-messages of docker-compose, docker not reachable for whatever reason... string-parsing is just one of the things that is bound to break somewhen. 

I think it would be a good addition to get a more structured output in this package to *any* of the commands, because everyone using this will currently write the same code to do the same things.

For this specific command, an output like this would be more appropriate:
```
{
    "address": "0.0.0.0",
    "originalPort": "33165"
}
```

So yeah, I'd like to see a generally changed output format like this:
```
{
  "raw": "<output>",
  "result": { "address": "0.0.0.0", "originalPort": "33165" }
}
```

**Comment by AlexZeitler** [comment]
@LarsKumbier That's exactly what I had in mind after reading the response from @Steveb-p. I think we should embrace this for each command/result.

We should use `interface`s for `result` which would allow users of the lib to use TypeScripts declaration merging if a property on `result` is missing due to newer `docker-compose`(the underlying tool) version.

> I think it would be a good addition to get a more structured output in this package to _any_ of the commands, because everyone using this will currently write the same code to do the same things.
> 
> For this specific command, an output like this would be more appropriate:
> 
> ```
> {
>     "address": "0.0.0.0",
>     "originalPort": "33165"
> }
> ```
> 
> So yeah, I'd like to see a generally changed output format like this:
> 
> ```
> {
>   "raw": "<output>",
>   "result": { "address": "0.0.0.0", "originalPort": "33165" }
> }
> ```

**Comment by stefanmeschke** [comment]
I really like the idea of

```
{
  "raw": "<output>",
  "result": { "address": "0.0.0.0", "originalPort": "33165" }
}
```

To be backward compatible it could be something like this:

```
export interface IDockerComposeResult<T> {
  exitCode: number | null;
  out: string;
  err: string;
  result: T;
}
```

**Comment by AlexZeitler** [comment]
Yes. @stefanmeschke Please create a new issue and copy [your suggestion](https://github.com/PDMLab/docker-compose/pull/52#issuecomment-533907539) and [your last answer](https://github.com/PDMLab/docker-compose/pull/52#issuecomment-533993954) from here as a starting point to it. 

Also please refer to this PR so we have everything tracked.

We should also define what `result` is in case of `err`.

**Comment by Steveb-p** [comment]
@stefanmeschke when output was not an address & port, what did you receive?

@AlexZeitler @stefanmeschke democratically I'm outvoted I guess :) and I do see the merit of what you want to do.

Can we open a new issue so we can check each and every call to `docker-compose` and decide when we're going with additional processing for them?

**Pull request merged**
