### PR TITLE
spawn instead of exec and piping child process output

### PR DESCRIPTION
**Pull request by zaucy**
For my use case I needed the output to pipe directly to the processes output instead of waiting for the command to finish. I also ran into a maxBuffer issue due to the use of `exec` so I switched it to spawn.

This should help with #15 and #14

### CODE REVIEW

**Comment by AlexZeitler** [comment]
Thanks. Please update this PR to include the changes from merged #8.

**Comment by zaucy** [comment]
Done!

**Comment by AlexZeitler** [comment]
@zaucy Somehow I merged to fast and tests fail:

```
TAP version 13
# ensure container gets started
Starting compose_test_apline ... 
Starting compose_test_apline ... done
not ok 1 test exited without ending
  ---
    operator: fail
  ...
not ok 2 test exited without ending
  ---
    operator: fail
  ...
not ok 3 test exited without ending
  ---
    operator: fail
  ...
not ok 4 test exited without ending
  ---
    operator: fail
  ...
not ok 5 test exited without ending
  ---
    operator: fail
  ...
not ok 6 test exited without ending
  ---
    operator: fail
  ...
not ok 7 test exited without ending
  ---
    operator: fail
  ...

1..7
# tests 7
# pass  0
# fail  7
```

**Comment by AlexZeitler** [comment]
Something like this makes it work:

```
  childProc = childProcess.spawn('docker-compose', concat, { cwd, env });
  if (options.log) {
    childProc.stdout.pipe(process.stdout);
    childProc.stderr.pipe(process.stderr);
    resolve();
  } else {
    resolve();
  }
```
Yet, when running the tests, they still fail as `resolve()` gets called to early if services need to be build/ images pulled etc.

**Pull request merged**
