### PR TITLE
feat: support docker compose v2 plugin version

### PR DESCRIPTION
**Pull request by AlexZeitler**
Solves #177

### CODE REVIEW

**Comment by AlexZeitler** [comment]
Currently I'm facing some issues with `docker compose` version ` v2.15.1` with the `stop` command: 

The command is executed without errors but it seems it didn't stop the container when the command exits because a check in our test fails.


```ts
  await compose.stop({ cwd: path.join(__dirname), log: logOutput })
  expect(await isContainerRunning('/compose_test_web')).toBeFalsy()
  expect(await isContainerRunning('/compose_test_proxy')).toBeFalsy()
```

**Comment by StefanScherer** [comment]
@AlexZeitler Interesting. Is there a simple repro case? I haven't looked into the code, but your failing test would be basically a `docker compose up -d` with two services, then later the `docker compose stop` and imediatelly a `docker compose ps`? And it worked with versions before 2.15.1, right?

**Comment by Steveb-p** [comment]
I would assume that `docker-compose` may report a container as stopping, while in reality it is still running. Don't see a reason otherwise. We are waiting for `docker-compose` process to complete, and adding a timeout fixing it seems to indicate that there is a slight delay between container being actually stopped.

**Comment by AlexZeitler** [comment]
> @AlexZeitler Interesting. Is there a simple repro case? I haven't looked into the code, but your failing test would be basically a `docker compose up -d` with two services, then later the `docker compose stop` and imediatelly a `docker compose ps`? And it worked with versions before 2.15.1, right?

@StefanScherer thanks for looping in.

That's the failing test which does what you suggested:

https://github.com/PDMLab/docker-compose/pull/228/files#diff-93d57c9e9cda34d9f45e5d57beddbf6436f7338ad591e47b7daa446d911f1201R204

**Comment by AlexZeitler** [comment]
> I would assume that `docker-compose` may report a container as stopping, while in reality it is still running. Don't see a reason otherwise. We are waiting for `docker-compose` process to complete, and adding a timeout fixing it seems to indicate that there is a slight delay between command being run and container being actually stopped.

Yes, that's my assumption as well.

A workaround could be to find the services started by the compose file, add `dockerode` as dependency as we do in the test and retry the check until the services are really stopped and only then return from our function.

**Comment by cristianrgreco** [comment]
> A workaround could be to find the services started by the compose file, add dockerode as dependency as we do in the test and retry the check until the services are really stopped and only then return from our function.

Would that involve moving dockerode from a test dependency to a dependency? Without pushing the instantiation of dockerode to the user it may be complex to add it, for example if the user is running a complex docker setup (dind, etc)

**Comment by AlexZeitler** [comment]
@cristianrgreco Yes, that true. We should find a better solution.

**Pull request merged**
