### PR TITLE
Provide ability to run docker-compose ps command

### PR DESCRIPTION
**Pull request by falinsky**

### CODE REVIEW

**Comment by AlexZeitler** [comment]
@falinsky Thanks for your contribution. Is this WiP oder ready to be merged?

**Comment by falinsky** [comment]
@AlexZeitler I believe it's ready to be merged. Also, it's covered with a few tests and checked via eslint.

**Comment by AlexZeitler** [comment]
Great, it is published on npmjs `@0.10.0`.

**Comment by falinsky** [comment]
@AlexZeitler thanks, awesome.

**Pull request merged**
