### PR TITLE
docker-compose build support

### PR DESCRIPTION
**Pull request by zaucy**
I used argument name `service` because of issue #9. I can change it to container to match the other methods if you would like.

If TypeScript was used (#10) the signature for the build function could be specified like so:

```TypeScript
build(service: string, options: IBuildOptions): Promise<string>
build(services: string[], options: IBuildOptions): Promise<string>
build(options: IBuildOptions): Promise<string>

build(arg0: string|string[]|IBuildOptions, arg1?: options: IBuildOptions) {
  // ...
}
```

I can understand not wanting to use the same name for each of the above signatures. I can rename them to `buildOne()`, `buildMany()`, `buildAll()` if you'd like.

### CODE REVIEW

**Comment by AlexZeitler** [comment]
Thanks for the PR. I would prefer `buildOne()`, `buildMany()`, `buildAll()`.

**Comment by zaucy** [comment]
Alright sounds good. I'll change them.

I'm curious if there is intended support for the other commands with the singular and many options such as `up`. Would there be an `upAll()` `upMany()` `upOne()`? I can add the different types to all of them if that sounds good to you.

**Comment by AlexZeitler** [comment]
Great, I created #18 for upAll() upMany() upOne().

**Comment by zaucy** [comment]
I changed `build()` to be `buildOne()`, `buildMany()` and `buildAll()`.

I also broke `exec()` and `run()` on my last PR with the spawn change. I included the fix here. The `execCompose()` was also not resolving it's promise, because spawn doesn't have a callback for an argument. Instead I listen to the stdout/stderr streams and construct a response object that is the same as the old version for backwards compatibility. Sorry about that!

**Comment by AlexZeitler** [comment]
Thanks, good job! :+1:

**Pull request merged**
