### PR TITLE
handle error based on exit code #2

### PR DESCRIPTION
**Pull request by Steveb-p**
Fixes tests related to #75 change and includes the original commit. Rebased due to conflict with release in package-lock.json.

Changes:
 * `close` event now properly rejects on exit code other than 0 (BREAKING CHANGE)
 * Tests are now migrated to Jest
 * Some tests did not clean properly, which was the reason why tests started failing
 * Allow omission of `options` argument (falls back to empty object)

### CODE REVIEW

**Comment by Steveb-p** [comment]
@AlexZeitler I've tried to find what is wrong with that `--workdir` test, but it seems that the error only occurs on CI? I'm kinda exhausted at this point and have run out of ideas :P

It seems it's unable to switch working directory properly.

You can see it in output in the last run for this PR. I'm leaving output set to true in that test until it's resolved.

On a side note, it might be worth it to stop rejecting when any message comes from stderr. It's probably not how we want it to behave and always wait for `exit` event instead.

**Comment by Steveb-p** [comment]
@AlexZeitler apparently CircleCI docker executor is incapable of mounting volumes to docker containers.

https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-mount-volumes-to-docker-containers-

I'm wondering how the tests worked previously with those mounts?

Since the related test is basically failing due to inability to mount a directory, I'll remove the need for mounting and check a system file instead. Is that ok?

**Comment by AlexZeitler** [comment]
@Steveb-p ok

**Comment by Steveb-p** [comment]
I'm pushing an updated tests then and see if it works.

Please **DO NOT** merge it, I'll rebase and squash all those commits into one.

**Comment by Steveb-p** [comment]
@AlexZeitler done. It should now properly pass all tests and should be ready for merging.

**Comment by AlexZeitler** [comment]
@Steveb-p Great job, thanks! 👌
📦 is on npm @ `0.19.0`

**Pull request merged**
