### PR TITLE
Update commands documentation

### PR DESCRIPTION
**Pull request by gautaz**
This PR mainly:

* fix the `port` command options
* order the command list alphabetically

I also wanted to update the `rm` command doc, but I was not sure how to document it...

### CODE REVIEW

**Comment by gautaz** [comment]
>  @gautaz thanks for your PR!

You're welcome!

> > I also wanted to update the rm command doc, but I was not sure how to document it...
> 
> What are your thoughts about it?

The TS signature is currently:
https://github.com/PDMLab/docker-compose/blob/d71e043be84f1fe59efc6571b86c3129f59fa8b0/src/index.ts#L296-L299

The `services` parameter is currently undocumented and as I am not fluent regarding TS parameters management, I was wondering how it should be used.
From a JS point of view, it feels strange to have a non optional parameter following an optional one...

**Comment by Steveb-p** [comment]
> The services parameter is currently undocumented and as I am not fluent regarding TS parameters management, I was wondering how it should be used.
> From a JS point of view, it feels strange to have a non optional parameter following an optional one...

Technically both parameters are optional. If there are no arguments following the first, `services` is resolved to an empty array.

**Comment by gautaz** [comment]
> Technically both parameters are optional. If there are no arguments following the first, `services` is resolved to an empty array.

I have just updated the PR to reflect this fact.
Tell me if you need me to change anything else :-).

**Comment by AlexZeitler** [comment]
@gautaz Below `down(options)` there seems to be something out of order:

image

**Comment by gautaz** [comment]
> @gautaz Below `down(options)` there seems to be something out of order:

Ooops! You're right, I should go back to elementary school ;-).

Fixed (hopefully).

**Comment by AlexZeitler** [comment]
@gautaz Awesome, thank you! Docs 📚 have been updated at https://pdmlab.github.io/docker-compose/

**Pull request merged**
